### ISSUE TITLE
Qgis 3.0

### ISSUE THREAD

**Issue by pekouille** [narimanInrap/ArcheoCAD#2]
Salut !

Tout d'abord, merci pour ce joli petit bout de programme !
Je me sers généralement de points2one pour créer mes polygones sur Qgis, mais j'utilise de plus en plus ton plugin, principalement pour les TP...
J'aurais voulu savoir si tu penses réécrire tout ça pour que ce soit compatible avec Qgis 3 ? (et donc savoir si je continue à l'utiliser ou si j'adapte mes méthodes pour une vie sans archeocad!)

Que ce soit le cas ou pas, encore merci d'avoir partagé, ça m'aura bien simplifié la vie !

Laurent (topo au CD62)

**Comment by narimanInrap** [comment]
Salut!

Merci pour ton message. Oui oui c'est prévu depuis un moment... mais j'ai eu d'autres trucs à faire entre temps et ça a pris un peu de retard...

bonne journée,

Nariman

**Comment by pekouille** [comment]
Ok, 
Super nouvelle, et un tout grand merci !

Laurent

**Comment by Spidergost** [comment]
Plutôt que de remplir une nouvelle Issue je lance un petit up ici pour savoir si ArcheoCAD 3.0 sortira bientôt.
