### ISSUE TITLE
it doesn't work

### ISSUE THREAD

**Issue by Forna73** [narimanInrap/ArcheoCAD#3]
Hi!
I'm on Qgis 3.16.
I've a point layer, I select your plug-in, but it doesn't let me do nothing!
I can't select any option and any layer from the window tool....

**Comment by m2cci-navenneg** [comment]
Hi
I'm experimenting the same troubles on most recent versions of Qgis 3. I still use ArcheoCAD on long therm release 3.10.2 and it works.
The plugin seems to need an update to work properly on latest Qgis soft. I hope somebody's working on it, let's wait...

**Comment by narimanInrap** [comment]
Hello,
I cannot reproduce the bug you're mentioning, don't know what to do... :-/

**Comment by narimanInrap** [comment]
the bug has been fixed
